### ISSUE TITLE
ijcnn labels

### ISSUE THREAD

**Issue by jlmelville** [rozyangno/sce#1]
Hello, how were the labels for the ijcnn dataset determined? All the obvious sources, e.g. <https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#ijcnn1>, <http://www.geocities.ws/ijcnn/nnc_ijcnn01.pdf>, <https://doi.org/10.1109/IJCNN.2001.939502> and the data itself only have two classes (engine fire or misfire). Both your papers [T-SNE Is Not Optimized to Reveal Clusters in Data](https://arxiv.org/abs/2110.02573) and [Stochastic Cluster Embedding](https://arxiv.org/abs/2108.08003) mention "ten engines (classes)" for this dataset, but the source at <http://www.geocities.ws/ijcnn/nnc_ijcnn01.pdf> only mentions a single (ten cylinder) engine. I do agree that the results seem to show ten distinct clusters, but I would like to understand how that was determined. Thanks!

**Comment by rozyangno** [comment]
It should be our typo. We meant ten cylinders. You can get the cluster labels simply by repeating ten as a group. For example, C(1:10:end) are for the first cylinder. Note that cluster order can vary up to a permutation.

**Comment by jlmelville** [comment]
@rozyangno thank you for getting back so quickly. I realized that the label might be related to the "cylinder identifier" (the integer encoding of the synchronization pulse) shortly after I sent this message. I understand now, thank you for the reply.

This is certainly an odd dataset given that nearly half the features are lagged versions of an indicator variable of whether the cylinder identifier == 10!

**Comment by rozyangno** [comment]
Yes, the dataset should be easy for clustering. But surprisingly, many current dimensionality reduction methods do not work well on it.
