### ISSUE TITLE
Reading the similary matrices in Python

### ISSUE THREAD

**Issue by dkobak** [rozyangno/sce#2]
Hi, I am trying to read in your similarity files in Python and I cannot find a way to do it. Here is my best attempt so far:

```
import h5py
arrays = {}
f = h5py.File('P_MNIST.mat', 'r')
for k, v in f['P'].items():
    arrays[k] = np.array(v)
```

which results in three arrays (data / ir / jc) of different shape

```
for a in arrays:
    print(a, arrays[a].shape)

# data (1085754,)
# ir (1085754,)
# jc (70001,)
```

and I do not understand how to convert this into a `scipy.sparse` matrix.

**Comment by dkobak** [comment]
Alternatively, are your similarity files perhaps also available somewhere in NPZ format instead of MAT?

**Comment by rozyangno** [comment]
I have uploaded a script for converting similarity matrices from .mat to .npz.
In short, Matlab sparse matrix is in the Scipy csc_matrix format.

**Comment by dkobak** [comment]
Thanks so much! Super helpful, and solves my issue.

**Comment by dkobak** [comment]
Hmm, actually this works on everything apart from FLOWCYTOMETRY and HIGGS. E.g.

```
h5py.File('P_FLOWCYTOMETRY.mat', 'r')
```

yields an `OSError: Unable to open file (file signature not found)` error, even though the file seems to be downloaded correctly. Here are file sizes, just as a sanity check:

```
-rw-rw-r--  1 dmitry dmitry  70255325 Okt  7 14:14 P_FLOWCYTOMETRY.mat
-rw-rw-r--  1 dmitry dmitry 306895183 Okt  7 12:16 P_HIGGS.mat
-rw-rw-r--  1 dmitry dmitry 275749201 Okt  7 12:15 P_IJCNN.mat
-rw-rw-r--  1 dmitry dmitry   2843239 Okt  7 12:44 P_MNIST.mat
-rw-rw-r--  1 dmitry dmitry 108292524 Okt  7 12:16 P_SHUTTLE.mat
-rw-rw-r--  1 dmitry dmitry   6184892 Okt  7 12:15 P_TOMORADAR.mat
```

**Comment by rozyangno** [comment]
It works for all data sets on my computer.
Anyway, I give the .npz shared links below. Hope they help you.
https://ntnu.box.com/s/f2fto98l5szpebn3cnwe08ni734smv5e
https://ntnu.box.com/s/hn02an4spvapgxe8h9hljkyfjexeqquf

**Comment by dkobak** [comment]
Thanks! I will give it a try. But can you check that my MAT filesizes are all correct?

**Comment by rozyangno** [comment]
No, they seem to be wrong
```
-rw-rw-r-- 1 yangzh yangzh  75729173 juni  19  2020 P_FLOWCYTOMETRY.mat
-rw-rw-r-- 1 yangzh yangzh 352156669 juni  19  2020 P_HIGGS.mat
-rw-rw-r-- 1 yangzh yangzh 275749201 juni  19  2020 P_IJCNN.mat
-rw-rw-r-- 1 yangzh yangzh   2843239 juni  19  2020 P_MNIST.mat
-rw-rw-r-- 1 yangzh yangzh 108292524 juni  19  2020 P_SHUTTLE.mat
-rw-rw-r-- 1 yangzh yangzh   6184892 juni  19  2020 P_TOMORADAR.mat
```

**Comment by dkobak** [comment]
I tried downloading them twice and always got the same result -- perhaps they were somehow corrupted during uploading to box.com?

**Comment by rozyangno** [comment]
Yes, you are right. I have re-uploaded the two .mat files. Now the sizes are correct.

**Comment by dkobak** [comment]
Great, it seems to work now! Closing this again.
