### ISSUE TITLE
Something may be wrong with similarity matrices for TOMORADAR, FLOWCYTOMETRY, and HIGGS

### ISSUE THREAD

**Issue by dkobak** [rozyangno/sce#3]
I downloaded similarity matrices for all datasets and ran t-SNE on all of them apart from HIGGS. Three datasets work fine and I get a reasonable result, but for two datasets (TOMORADAR and FLOWCYTOMETRY) something is terribly wrong. I am using a t-SNE implementation that can easily handle 1M sample size. Also, I am processing all datasets in a loop, so the code is identical and it's very unlikely that there is some mistake on my side.

Fir those datasets, I get nonsensical KL divergence from the beginning of the optimization:

```
===> Running optimization with exaggeration=12.00, lr=200.00 for 250 iterations...
Iteration   50, KL divergence 202913310.5925, 50 iterations in 4.8980 sec
Iteration  100, KL divergence 202492001.2561, 50 iterations in 6.3112 sec
...
```

I suspect something may be wrong with the similarity matrices.

![tsnes](https://user-images.githubusercontent.com/8970231/194600156-64910bbe-dd19-4b41-8f9b-4eb9a72318a1.png)

For HIGGS, I only ran it for 50 iterations, but the KL divergence is similarly nonsensical.

**Comment by dkobak** [comment]
@rozyangno What do you think? I could get the raw data and generate similarity matrices myself, but ideally I would use exactly the same similarity matrices that you used...

**Comment by rozyangno** [comment]
It is expected that t-SNE fails. This is exactly what our paper wants to show: t-SNE may not show data clusters even if the given similarity matrix is well-clustered.

**Comment by dkobak** [comment]
Sure, but for the first three datasets I get the same tSNE picture as you do, while for TOMORADAR, FLOWCYTOMETRY, and HIGGS I get a complete mess -- very different from your tSNE pictures. Also, KL divergence should normally be like 10 or something like that after 50 epochs, and not >10^9.

I suspect that the affinity matrices are somehow saved/exported/loaded incorrectly... Maybe you want to double check e.g. for TOMORADAR that if you grab the affinity matrix from the MAT file on BOX, then you can reproduce your tSNE or SCE result...

**Comment by rozyangno** [comment]
t-SNE indeed gives a mess for TOMORADAR, FLOWCYTOMETRY, and HIGGS, even on my computer.
I used van der Maatens' own t-SNE implementation https://github.com/lvdmaaten/bhtsne. I have tried opt-TSNE, but it fails as well.

**Comment by dkobak** [comment]
But it is a different kind of mess! :-) Please compare your tSNE of TOMORADAR as shown here

https://raw.githubusercontent.com/rozyangno/sce/main/figures/tomoradar_tsne.png

and the tSNE I obtained as shown here 

https://user-images.githubusercontent.com/8970231/194600156-64910bbe-dd19-4b41-8f9b-4eb9a72318a1.png

As I said, I suspect that I was running tSNE on a different similarity matrix, compared to you. For the first three datasets the agreement between your tSNE and my tSNE if very good.

**Comment by rozyangno** [comment]
I don't see your point. The repo is for SCE. If you find SCE fails for the given similarity matrix, then I will fix it as soon as possible. Otherwise, why should I guarantee different t-SNE runs must give exactly the same mess?

**Comment by dkobak** [comment]
Okay -- unfortunately I don't have SCE set up (yet) and not sure it will run on my laptop without a dedicated GPU. But I can try.

I thought the figure I posted is indicative of some problem in the similarity matrix, but if you think it's not, then I will try to demonstrate it using SCE.

**Comment by rozyangno** [comment]
One more thing: I used 10000 iterations (default=1000) in van der Maaten's t-SNE program to ensure convergence.

**Comment by dkobak** [comment]
I think I found out what the problem was. For TOMORADAR, the similarity matrix sums to 7643230 (which is the number of elements in there) and not to 1 (as t-SNE expects). If I normalize, it works.

For MNIST and other datasets, it was normalized already.

**Comment by rozyangno** [comment]
Good that you find the reason. I add a note on the home page about the normalization.
